name: AC-CommonLib
version: '${project.version}'
main: tk.airshipcraft.commonlib.CommonLib
api-version: 1.19
authors: [ notzune ]
description: Plugin library for AirshipCraft
website: https://www.airshipcraft.tk/docs/book
folia-supported: true
