name: Generate and Publish Javadoc

on:
  push:
    branches:
      - main

jobs:
  javadoc:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Generate Javadoc
        run: mvn javadoc:javadoc -Dmaven.javadoc.failOnError=false

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./target/site/apidocs/
