name: Maven Build and Release

on:
  release:
    types: [created] # Trigger when a new release is created

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Load Environment Variables
        run: .github/scripts/set-env-vars.sh

      - name: Checkout code
        uses: ./.github/workflows/actions/checkout

      - name: Setup JDK
        uses: ./.github/workflows/actions/setup-java
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Maven packages
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Extract GitHub release tag
        run: echo "RELEASE_VERSION=$(echo ${GITHUB_REF#refs/tags/} | cut -c 2-)" >> $GITHUB_ENV

      - name: Print release version
        run: echo "Release version is ${{ env.RELEASE_VERSION }}"

      - name: Update Maven project version
        run: mvn versions:set -DnewVersion=${{ env.RELEASE_VERSION }} -X

      - name: Commit updated pom.xml
        run: ./.github/workflows/scripts/commit-updates
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Maven Clean Install
        run: mvn clean install

      - name: Upload JAR files to GitHub Release
        uses: ./.github/workflows/actions/upload-release-asset
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./target/${{ env.ARTIFACT_NAME }}-${{ env.RELEASE_VERSION }}.jar
          asset_name: ${{ env.ARTIFACT_NAME }}-${{ env.RELEASE_VERSION }}.jar
          asset_content_type: application/java-archive
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
