name: Maven Package and Deploy

on:
  workflow_run:
    workflows: [ "Maven Build and Release" ]
    types:
      - completed

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout code
        uses: .github/workflows/actions/checkout

      - name: Load Environment Variables
        run: .github/workflows/scripts/set-env-vars.sh

      - name: Setup JDK
        uses: .github/workflows/actions/setup-java
        with:
          java-version: ${{ env.JAVA_VERSION }}

      - name: Cache Maven packages
        uses: .github/workflows/actions/cache-maven

      - name: Build with Maven
        run: mvn clean install

      - name: Create settings.xml
        run: .github/workflows/scripts/create-settings-xml
        shell: bash

      - name: Deploy to Sonatype
        run: mvn deploy -DskipTests
        env:
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
