name: TODO Management

on:
  push:
    branches: 
      - '**'  # This will trigger the workflow on push to any branch
  issues:
    types: [opened, closed, deleted]

jobs:
  manage-todo:
    runs-on: ubuntu-latest
    steps:
      - name: Load Environment Variables
        run: .github/scripts/set-env-vars.sh
        
      - name: Checkout code
        uses: ./.github/workflows/actions/checkout
        with:
          fetch-depth: 0  # Fetch all history for all branches and tags


      - name: Set up Python
        uses: ./.github/workflows/actions/setup-python
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Extract branch name
        shell: bash
        run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
        id: extract_branch

      - name: Run Todo Manager Script
        run: python ./.github/workflows/scripts/todo_manager.py
        env:
          GITHUB_ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          JAVA_FILES_DIRECTORY: 'src/'
          GITHUB_ISSUE_TITLE: ${{ github.event.issue.title }}
          GITHUB_ISSUE_BODY: ${{ github.event.issue.body }}

      - name: Commit and Push Changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'github-actions@github.com'
          git add -A
          git commit -m "Automated TODO management" || echo "No changes to commit"
          git push origin ${{ steps.extract_branch.outputs.branch }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
